apiVersion: v1
kind: Namespace
metadata:
  name: github-actions-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: github-actions-test
  labels:
    app: github-actions-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-actions-test
  template:
    metadata:
      labels:
        app: github-actions-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-actions-test-ingress
  namespace: github-actions-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /github-actions-test
        pathType: Prefix
        backend:
          service:
            name: github-actions-test-service
            port:
              name: http
  tls:
  - hosts:
    - example.com
    secretName: tls-secret-name
